### ISSUE TITLE
I want to know how to use it.

### ISSUE THREAD

**Issue by JiwonAhn21** [felixhummel/g27#1]
hi :)
I want to get data from steering wheel, like rotation degree, force, and so on.
I'm using g27. 
so is there tutorial for this python file?
is it possible to use this software while I'm playing euro truck simulator 2? 
Thanks for your work!

**Comment by felixhummel** [comment]
hi!

Sorry to disappoint. This was just a quick draft. No tutorial, just the source.
You can adopt this, if you want.
I do not have the time to maintain this.

**Comment by felixhummel** [comment]
Also this runs on Linux only, because you need `/dev/input/js0` (see [here](https://github.com/felixhummel/g27/blob/master/g27.py#L192)).

Closing this for now. Feel free to add a ticket if you want to take over this repo! :)
